name: Five Minute Scheduler

on:
  pull_request:
    types: [opened, reopened]
  schedule:
    # 매 5분마다 실행
    - cron: "*/5 * * * *"

jobs:
  run-scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run scheduled task
        run: |
          echo "이 작업이 5분마다 실행됩니다."
          echo "현재 시간: $(date)"

      # 여기에 5분마다 실행하고 싶은 추가 작업들을 넣을 수 있습니다.
